Feature/migration
E-A-D-S/beacademy-devstart-rubi pull request #3
Opened 2022-07-02 00:15 UTC by tharsila

Poderiam realizar o review dessa atualização.

2022-07-02 02:41 UTC, Elivandro requested changes
cancela a exclusão do arquivo .env-exemple https://github.com/E-A-D-S/beacademy-devstart-rubi/pull/3/commits/e65e99b8753bbc93e4ade88d3449c19714d912b3

ou,
teremos problemas no futuro quando alguém fizer um clone disso aí.

falta "addresses" e "phones", para finalizar a migration de users.

2022-07-02 02:58 UTC, E-A-D-S approved these changes
ok

2022-07-02 14:32 UTC, Elivandro commented
Addresses e phones pode ser feito em uma "tabela" separada podemos buscar fazendo a relação de id.

2022-07-02 21:07 UTC, renatadeodorio approved these changes

2022-07-02 21:08 UTC, renatadeodorio commented on app/Models/User.php
> +        'userType'
Acrescentar Cep -postal code

2022-07-02 21:09 UTC, renatadeodorio approved these changes

2022-07-02 21:10 UTC, renatadeodorio approved these changes

2022-07-02 21:10 UTC, renatadeodorio approved these changes

2022-07-02 22:49 UTC, bielmariano reviewed
Falta address, phone e birthDate.
Sugestão a ser discutida com o time:
Um só atributo de address ou dividir nos seguintes atributos: rua, número, complemento, setor/bairro.

2022-07-03 03:18 UTC, MatheusSGomes approved these changes

2022-07-04 15:00 UTC, Elivandro requested changes
por min está ok agora,
todas as fillables estão prontas para ser associadas as tabelas estrangeiras.

2022-07-04 15:00 UTC, Elivandro commented on app/Models/User.php
> +        'userType'
boa, bem lembrado... cep vai andar em conjunto com addresses.

2022-07-04 15:18 UTC, Elivandro approved these changes

2022-07-04 15:18 UTC, merged